import CommentSection from './CommentSection/CommentSection';
import ModalCreateNewList from './ModalCreateNewList/ModalCreateNewList';

export { default as Banner } from './Banner/Banner';
export { default as Navbar } from './Banner/Nav/Nav';
export { default as MovieCard } from './MovieCard/MovieCard';
export { default as CategorySection } from './filterCategories/filterCategories';
export { default as AddMoviesModal } from './addMoviesModal/addMoviesModal';
export { default as ButtonCustom } from './ButtonCustom/ButtonCustom';
export { default as ActionAndIcon } from './ActionAndIcon/ActionAndIcon';
export { default as FilterList } from './FilterList/FilterList';
export { default as FigureMovie } from './FigureMovie/FigureMovie';
export { default as DescriptionMovie } from './description/description';
export { default as ExtraInfo } from './ExtraInfo/ExtraInfo';
export { default as SessionForm } from './SessionForm/SessionForm';
export { default as SubmitAndTerms } from './SubmitAndTerms/SubmitAndTerms';
export { default as MovieCardAdd } from './MovieCardADD/MovieCardADD';
export { default as ModalCreateNewList } from './ModalCreateNewList/ModalCreateNewList';
export { default as CommentSection } from './CommentSection/CommentSection';
export { default as FavoriteMovies } from './FavoriteMovies/FavoriteMovies';
export { default as ProfileInfo } from './ProfileInfo/ProfileInfo';
